# Generated by Django 6.0.5 on 2026-05-06 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('course', models.PositiveSmallIntegerField()),
                ('curator', models.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curated_groups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('inn', models.CharField(max_length=14, unique=True)),
                ('id_cart', models.CharField(max_length=9, unique=True)),
                ('phone', models.CharField(max_length=12)),
                ('second_phone', models.CharField(blank=True, max_length=12, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='students.group')),
            ],
        ),
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('relation', models.CharField(choices=[('father', 'Папа'), ('mother', 'Мама'), ('brother', 'Брат'), ('sister', 'Сестра'), ('grandfather', 'Дедушка'), ('grandmother', 'Бабушка'), ('uncle', 'Дядя'), ('aunt', 'Тётя'), ('other', 'Другое')], max_length=30)),
                ('phone', models.CharField(max_length=12)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='students.student')),
            ],
        ),
    ]
